---
title: 'Data Project #2'
author: "Brennan Nick"
date: "11/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
```

```{r}
library(tidyverse)
library(sf)
library(tigris)
library(leaflet)
library(censusapi)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

acs_vars_2019_1yr <-
  listCensusMetadata(
    name = "2019/acs/acs1",
    type = "variables"
  )
```


```{r}
alameda_education_race <-
  1:7 %>% 
  map_dfr(function(x){
    getCensus(
      name = "acs/acs1",
      vintage = 2019,
      region = "county:001",
      regionin = "state:06",
      vars = paste0("group(B15002",LETTERS[x],")")
    ) %>%
      select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
      pivot_longer(
        ends_with("E"),
        names_to = "variable",
        values_to = "estimate"
      ) %>%
      left_join(
        acs_vars_2019_1yr %>% 
          select(name, label), 
        by = c("variable" = "name")
      ) %>% 
      select(-variable) %>% 
      separate(
        label,
        into = c(NA,NA,NA,"education"),
        sep = "!!"
      ) %>% 
      filter(!is.na(education)) %>% 
      mutate(race = census_race_labels[x])
  })
```



```{r}
alameda_education_race %>% 
  group_by(education, race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  rbind(
    alameda_education_race %>%
      filter(county == "001") %>% 
      group_by(race) %>% 
      summarize(estimate = sum(estimate)) %>% 
      mutate(education = "Total")
  ) %>%
  ggplot() +
  geom_bar(
    aes(
      x = education %>% factor(),
      y = estimate,
      fill = race
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Household edcuation",
    y = "Number of households",
    title = "Riverside household education by race",
    fill = "Race of householder"
  ) +
  coord_flip()
```

```{r}
graph<-
  alameda_education_race %>% 
  group_by(education, race) %>% 
  summarize(estimate = sum(estimate)) %>%
rbind(
 alameda_education_race %>%
    group_by(race) %>% 
    summarize(estimate = sum(estimate)) %>% 
    mutate(education = "Total")
)%>% 
  ggplot() +
  geom_bar(
    aes(
      x = education %>% 
        factor(levels = rev(c("Total", alameda_education_race$education[1:8]))),
      y = estimate,
      fill = race
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "Household education",
    y = "Proportion of households",
    title = "Alameda household education by race",
    fill = "Race of householder"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )
graph
```
##############################################################################

```{r}
temp <- tempfile()
download.file("https://www2.census.gov/programs-surveys/acs/data/pums/2018/5-Year/csv_hca.zip",destfile = temp, mode = "wb")

pums_hca_2018_5yr <- read_csv(unzip(temp,"psam_h06.csv"))

unlink(temp)
```

```{r}
install.packages("devtools")

devtools::install_github("walkerke/tidycensus")
```

```{r}
library(tidycensus)

census_api_key("c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

pums_vars_2018 <- 
  pums_variables %>%
  filter(year == 2018, survey == "acs5")

pums_vars_2018_distinct_hh <- 
  pums_vars_2018 %>%
  distinct(var_code, var_label, data_type, level) %>% 
  filter(level == "housing")
```

```{r}
# ca_pums <- get_pums(
#   variables = c(
#     "PUMA",
#     "AGEP",
#     "SCHG",
#     "ACCESS"
#   ),
#   state = "CA",
#   year = 2018,
#   survey = "acs5",
#   recode = T
# )
# saveRDS(ca_pums,"PUBLPOL 118X CA_PUMS.rds")

ca_pums <- readRDS("PUBLPOL 118X CA_PUMS.rds")
```

```{r}
alameda_county <- counties("CA", cb=TRUE, progress_bar=F) %>% 
  filter(NAME=="Alameda")
library(mapview)

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

alameda_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[alameda_county, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

alameda_pums <-
  ca_pums %>% 
  filter(PUMA %in% alameda_pumas$PUMACE10)
```

```{r}
alameda_pums_internet <-
  alameda_pums %>% 
  mutate(
    SCHG = SCHG %>% as.numeric(),
    k12 = ifelse(
      SCHG < 15,
      PWGTP,
      0
    ),
    k12_nointernet = ifelse(
      SCHG < 15 & ACCESS == "3",
      PWGTP,
      0
    )
  ) %>% 
  group_by(PUMA) %>% 
  summarize(
    perc_k12_nointernet =
      sum(k12_nointernet, na.rm = T)/sum(k12, na.rm = T)*100
  ) %>% 
  left_join(
    alameda_pumas %>% 
      select(PUMACE10),
    by = c("PUMA" = "PUMACE10")
  ) %>% 
  st_as_sf()
pums_pal <- colorNumeric(
  palette = "Purples",
  domain = alameda_pums_internet$perc_k12_nointernet
)


leaflet() %>%
  addTiles() %>% 
  addPolygons(
    data = alameda_pums_internet,
    fillColor = ~pums_pal(perc_k12_nointernet),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste0(
      round(perc_k12_nointernet), 
      "% K-12 students without internet"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = alameda_pums_internet,
    pal = pums_pal,
    values = ~perc_k12_nointernet,
    title = "% K-12 students without internet"
  )
```
##########################################################################





```{r}
alameda_mobility_current_19 <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:001",
    regionin = "state:06",
    vars = c("group(B07009)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"mobility","education"),
    sep = "!!"
  ) %>% 
  mutate(
    mobility = ifelse(
      mobility %in% c("Same house 1 year ago:", "Moved within same county:"),
      "Here since last year",
      "Inflow"
    )
  ) %>% 
  filter(!is.na(education)) %>% 
  group_by(mobility, education) %>% 
  summarize(estimate = sum(estimate))
```

```{r}
alameda_mobility_lastyear_19 <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2019,
    region = "county:001",
    regionin = "state:06",
    vars = c("group(B07409)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"mobility","education"),
    sep = "!!"
  ) %>% 
  mutate(
    mobility = ifelse(
      mobility %in% c("Same house:", "Moved within same county:"),
      "Here since last year",
      "Outflow"
    )
  ) %>% 
  filter(!is.na(education)) %>% 
  group_by(mobility, education) %>% 
  summarize(estimate = sum(estimate))
```

```{r}
alameda_mobility_current_18 <- 
  getCensus(
    name = "acs/acs1",
    vintage = 2018,
    region = "county:001",
    regionin = "state:06",
    vars = c("group(B07009)")
  ) %>% 
  select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_1yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"mobility","education"),
    sep = "!!"
  ) %>% 
  mutate(
    mobility = "Here last year"
  ) %>% 
  filter(!is.na(education)) %>% 
  group_by(mobility, education) %>% 
  summarize(estimate = sum(estimate))
```

```{r}
alameda_flows_19 <-
  rbind(
    alameda_mobility_current_18,
    alameda_mobility_lastyear_19 %>% 
      filter(mobility == "Outflow"),
    alameda_mobility_current_19 %>% 
      filter(mobility == "Inflow"),
    alameda_mobility_current_19 %>% 
      group_by(education) %>% 
      summarize(estimate = sum(estimate)) %>% 
      mutate(mobility = "Here this year")
  ) %>% 
  pivot_wider(
    names_from = mobility,
    values_from = estimate
  ) %>% 
  mutate(
    `External net` = Inflow - Outflow,
    `Internal net` = `Here this year` - `Here last year` - `External net`,
    `Educational attainment` = education %>% factor(levels = c(
      "Less than high school graduate",
      "High school graduate (includes equivalency)",
      "Some college or associate's degree",
      "Bachelor's degree",
      "Graduate or professional degree"
  ))) %>% 
  select(
    `Educational attainment`, 
    `Internal net`,
    `External net`,
    `Here last year`, 
    `Here this year`, 
    Outflow, 
    Inflow
  )

alameda_flows_19
```
#These numbers describe the number of people who are in Alameda county who now have Bachelor's degrees, not counting new people with degrees moving in.





